language: go
go:
  - 1.8
  - 1.9
  - tip
env:
  global:
    - VERSION=$(subst heads/,,$(shell git describe --all))
    - TAG=$(shell git rev-parse --short HEAD)
install:
  - "go get -d -v ./..."
  - "go build -v ./..."

before_deploy:
  - mkdir -p release
  - "GOOS=linux  GOARCH=amd64 go build -o release/env2template-v$VERSION-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o release/env2template-v$VERSION-darwin-amd64"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 2TqvGgi54G251g1KQ_EZtQ
  file:
    - release/env2template-v$VERSION-linux-amd64
    - release/env2template-v$VERSION-darwin-amd64
  on:
    repo: archsh/env2template
    tags: true